'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import Navbar from '@/app/components/Navbar'

export default function SmartLabelsPage() {
  const [products, setProducts] = useState([])
  const [profile, setProfile] = useState(null)
  const [loading, setLoading] = useState(true)
  const [selectedProducts, setSelectedProducts] = useState([])
  const [labelType, setLabelType] = useState('qr')
  const [labelSize, setLabelSize] = useState('medium')
  const [exhibitionName, setExhibitionName] = useState('')
  const [showPreview, setShowPreview] = useState(false)
  const router = useRouter()
  const supabase = createClient()

  useEffect(() => {
    loadData()
  }, [])

  async function loadData() {
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) { router.push('/login'); return }
    const { data: profileData } = await supabase.from('profiles').select('*').eq('id', user.id).single()
    setProfile(profileData)
    const { data: productsData } = await supabase.from('products').select('*').eq('manufacturer_id', user.id)
    setProducts(productsData || [])
    setLoading(false)
  }

  function toggleProduct(id) {
    if (selectedProducts.includes(id)) {
      setSelectedProducts(selectedProducts.filter(p => p !== id))
    } else {
      setSelectedProducts([...selectedProducts, id])
    }
  }

  function selectAll() {
    if (selectedProducts.length === products.length) {
      setSelectedProducts([])
    } else {
      setSelectedProducts(products.map(p => p.id))
    }
  }

  function getSelectedData() {
    return products.filter(p => selectedProducts.includes(p.id))
  }

  async function saveExhibition() {
    if (!exhibitionName) {
      alert('Please enter exhibition name')
      return
    }
    
    const { data: { user } } = await supabase.auth.getUser()
    const { error } = await supabase.from('exhibitions').insert({
      manufacturer_id: user.id,
      name: exhibitionName,
      location: 'Showroom',
      start_date: new Date().toISOString(),
      status: 'active'
    })
    
    if (error) {
      alert('Error: ' + error.message)
    } else {
      alert('Exhibition session created!')
    }
  }

  function printLabels() {
    const selected = getSelectedData()
    if (selected.length === 0) {
      alert('Please select at least one product')
      return
    }
    
    const sizeStyles = {
      small: { width: '50mm', padding: '5mm' },
      medium: { width: '70mm', padding: '10mm' },
      large: { width: '100mm', padding: '15mm' }
    }
    
    const style = sizeStyles[labelSize]
    
    const printWindow = window.open('', '_blank')
    let html = `<!DOCTYPE html>
    <html>
    <head>
      <title>Smart Labels - ${profile?.company_name}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        .label-container { display: flex; flex-wrap: wrap; gap: 20px; }
        .label {
          width: ${style.width};
          padding: ${style.padding};
          border: 1px solid #ddd;
          border-radius: 8px;
          text-align: center;
          page-break-inside: avoid;
          break-inside: avoid;
        }
        .label img { width: 100%; max-width: 150px; height: auto; }
        .product-name { font-weight: bold; font-size: 14px; margin: 8px 0; }
        .product-price { color: #0891b2; font-size: 16px; font-weight: bold; }
        .label-code { font-size: 10px; color: #666; margin-top: 5px; }
        .label-type { font-size: 10px; color: #999; margin-top: 3px; }
        @media print {
          body { margin: 0; padding: 0; }
          .label-container { gap: 10px; }
          .label { break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <h2 style="text-align:center">Smart Labels - ${profile?.company_name}</h2>
      <p style="text-align:center">${exhibitionName || 'Product Exhibition'}</p>
      <div class="label-container">`
    
    selected.forEach(p => {
      const url = `${window.location.origin}/products/${p.id}`
      const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(url)}`
      html += `
        <div class="label">
          <img src="${qrUrl}" />
          <div class="product-name">${p.title}</div>
          <div class="product-price">${p.currency === 'INR' ? '₹' : '$'}${p.price_per_unit}</div>
          <div class="label-code">ID: ${p.id.substring(0, 8)}</div>
          <div class="label-type">${labelType.toUpperCase()} Label</div>
        </div>`
    })
    
    html += `
      </div>
      <p style="text-align:center; margin-top: 30px; font-size:12px; color:#666;">
        Scan QR code to view product details | Generated by Midlync
      </p>
    </body>
    </html>`
    
    printWindow?.document.write(html)
    printWindow?.document.close()
    printWindow?.print()
  }

  if (loading) return <div className="min-h-screen bg-slate-50 flex items-center justify-center">Loading...</div>

  return (
    <div className="min-h-screen bg-slate-50">
      <Navbar role="manufacturer" companyName={profile?.company_name || 'Manufacturer'} />

      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h1 className="text-2xl font-bold">Smart Labels (QR/RFID)</h1>
            <p className="text-slate-500 text-sm">Generate QR codes for exhibition, showroom, and product tracking</p>
          </div>
          <button onClick={() => router.push('/manufacturer/dashboard')} className="text-slate-600 hover:text-slate-800">← Back</button>
        </div>

        {/* Exhibition Setup */}
        <div className="bg-white rounded-xl p-5 mb-6 shadow-sm">
          <h2 className="font-semibold mb-3">Exhibition / Showroom Setup</h2>
          <div className="grid md:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-semibold mb-1">Exhibition Name</label>
              <input type="text" placeholder="e.g., TexFair 2024, Mumbai Showroom" value={exhibitionName} onChange={e => setExhibitionName(e.target.value)}
                className="w-full border rounded-lg px-4 py-2" />
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">Label Type</label>
              <select value={labelType} onChange={e => setLabelType(e.target.value)} className="w-full border rounded-lg px-4 py-2">
                <option value="qr">QR Code (Printable)</option>
                <option value="rfid">RFID Ready</option>
                <option value="nfc">NFC Compatible</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-semibold mb-1">Label Size</label>
              <select value={labelSize} onChange={e => setLabelSize(e.target.value)} className="w-full border rounded-lg px-4 py-2">
                <option value="small">Small (50mm)</option>
                <option value="medium">Medium (70mm)</option>
                <option value="large">Large (100mm)</option>
              </select>
            </div>
          </div>
          <button onClick={saveExhibition} className="mt-4 bg-cyan-600 text-white px-4 py-2 rounded-lg">Save Exhibition Session</button>
        </div>

        {/* Product Selection */}
        <div className="bg-white rounded-xl p-5 mb-6 shadow-sm">
          <div className="flex justify-between items-center mb-4">
            <h2 className="font-semibold">Select Products for Smart Labels</h2>
            <button onClick={selectAll} className="text-sm text-cyan-600 hover:underline">
              {selectedProducts.length === products.length ? 'Deselect All' : 'Select All'}
            </button>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 max-h-60 overflow-y-auto">
            {products.map(p => (
              <label key={p.id} className="flex items-center gap-2 text-sm p-2 border rounded-lg hover:bg-slate-50 cursor-pointer">
                <input type="checkbox" checked={selectedProducts.includes(p.id)} onChange={() => toggleProduct(p.id)} />
                <span className="truncate flex-1">{p.title}</span>
                <span className="text-cyan-600 text-xs">${p.price_per_unit}</span>
              </label>
            ))}
          </div>
          {products.length === 0 && <p className="text-slate-400 text-center py-4">No products found. Add products first.</p>}
        </div>

        {/* Preview & Print */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <button onClick={() => setShowPreview(true)} disabled={selectedProducts.length === 0}
            className="bg-slate-600 hover:bg-slate-700 text-white py-3 rounded-xl font-semibold disabled:opacity-50 transition">
            👁 Preview Labels
          </button>
          <button onClick={printLabels} disabled={selectedProducts.length === 0}
            className="bg-purple-600 hover:bg-purple-700 text-white py-3 rounded-xl font-semibold disabled:opacity-50 transition">
            🖨️ Print Smart Labels
          </button>
        </div>

        <div className="mt-4 text-center text-sm text-slate-500">
          {selectedProducts.length} product(s) selected for label printing
        </div>

        {/* Preview Modal */}
        {showPreview && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 overflow-auto" onClick={() => setShowPreview(false)}>
            <div className="bg-white rounded-2xl max-w-2xl w-full p-6" onClick={e => e.stopPropagation()}>
              <h2 className="text-xl font-bold mb-4">Label Preview</h2>
              <div className="grid grid-cols-2 gap-4">
                {getSelectedData().slice(0, 4).map(p => {
                  const url = `${window.location.origin}/products/${p.id}`
                  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(url)}`
                  return (
                    <div key={p.id} className="border rounded-lg p-4 text-center">
                      <img src={qrUrl} className="w-32 h-32 mx-auto mb-2" />
                      <p className="font-medium text-sm">{p.title}</p>
                      <p className="text-cyan-600 font-bold text-sm">${p.price_per_unit}</p>
                    </div>
                  )
                })}
              </div>
              <button onClick={() => setShowPreview(false)} className="w-full mt-4 border py-2 rounded-lg">Close</button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}